### ISSUE TITLE
Uncaught TypeError when using V8 with envjs 1.3 on Linux Box 64 bits

### ISSUE THREAD

**Issue by falaise** [cowboyd/therubyracer#68]
Hello,

My configuration :
Linux Fedora 14 on PC core 2 64 bits
Ruby 1.9.2p136 and/or 1.8.7p330.
therubyracer-heroku-0.8.1 because therubyracer doesn't compile on Linux 64b with gcc 4.5.1.
env-js 1.3 pre.

A very simple test  from the file envjs/rubyracer.rb :

require 'rubygems'

require 'v8'

class Runtime
  def new_context()
    V8::Context.new
  end
  def configure_context(runtime, context)
    ruby = {}
    [:Set, :SortedSet].each{ |c| 
       ruby[c.to_s] = Kernel.eval(c.to_s)
    }
    context['Ruby'] = ruby
  end
end

runtime = Runtime.new
global = runtime.new_context()
begin
  runtime.configure_context(runtime, global)
rescue => ex
  puts " EXCEPTION ex=<#{ex}> (#{ex.message})\n STACK=<#{ex.backtrace.join("\n")}>"
end

And you have those exception :

<unknown>:-1: Uncaught TypeError: Cannot convert object to primitive value
 EXCEPTION ex=<undefined method `SetHiddenValue' for #<V8::C::Value:0x0000000172acf8>> (undefined method `SetHiddenValue' for #<V8::C::Value:0x0000000172acf8>)
 STACK=<ruby-192p136/lib/ruby/gems/1.9.1/gems/therubyracer-heroku-0.8.1.pre3/lib/v8/portal.rb:118:in`block in v8'
ruby-192p136/lib/ruby/gems/1.9.1/gems/therubyracer-heroku-0.8.1.pre3/lib/v8/portal.rb:117:in `tap'
ruby-192p136/lib/ruby/gems/1.9.1/gems/therubyracer-heroku-0.8.1.pre3/lib/v8/portal.rb:117:in`v8'
ruby-192p136/lib/ruby/gems/1.9.1/gems/therubyracer-heroku-0.8.1.pre3/lib/v8/portal.rb:111:in `block (2 levels) in v8'
ruby-192p136/lib/ruby/gems/1.9.1/gems/therubyracer-heroku-0.8.1.pre3/lib/v8/portal.rb:110:in`each'
ruby-192p136/lib/ruby/gems/1.9.1/gems/therubyracer-heroku-0.8.1.pre3/lib/v8/portal.rb:110:in `block in v8'
ruby-192p136/lib/ruby/gems/1.9.1/gems/therubyracer-heroku-0.8.1.pre3/lib/v8/portal.rb:109:in`tap'
ruby-192p136/lib/ruby/gems/1.9.1/gems/therubyracer-heroku-0.8.1.pre3/lib/v8/portal.rb:109:in `v8'
ruby-192p136/lib/ruby/gems/1.9.1/gems/therubyracer-heroku-0.8.1.pre3/lib/v8/object.rb:19:in`block (2 levels) in []='
ruby-192p136/lib/ruby/gems/1.9.1/gems/therubyracer-heroku-0.8.1.pre3/lib/v8/portal.rb:75:in `block in open'
ruby-192p136/lib/ruby/gems/1.9.1/gems/therubyracer-heroku-0.8.1.pre3/lib/v8/context.rb:79:in`enter'
ruby-192p136/lib/ruby/gems/1.9.1/gems/therubyracer-heroku-0.8.1.pre3/lib/v8/portal.rb:74:in `open'
ruby-192p136/lib/ruby/gems/1.9.1/gems/therubyracer-heroku-0.8.1.pre3/lib/v8/object.rb:18:in`block in []='
ruby-192p136/lib/ruby/gems/1.9.1/gems/therubyracer-heroku-0.8.1.pre3/lib/v8/object.rb:17:in `tap'
ruby-192p136/lib/ruby/gems/1.9.1/gems/therubyracer-heroku-0.8.1.pre3/lib/v8/object.rb:17:in`[]='
ruby-192p136/lib/ruby/gems/1.9.1/gems/therubyracer-heroku-0.8.1.pre3/lib/v8/context.rb:58:in `[]='
:in`configure_context'
:in `<main>'>

It ONLY fails if you use the TWO Symbols  (:Set AND :SortedSet).

Any idea ?

Regards.
