### ISSUE TITLE
Support for Windows/MinGW

### ISSUE THREAD

**Issue by nevele** [cowboyd/therubyracer#44]
working with 2.3.3 now, compiles everything, same issue when linking the shared object:

g++ -shared -s -o v8.so rr.o v8.o v8_array.o v8_callbacks.o v8_cxt.o v8_date.o v8_exception.o v8_external.o v8_func.o v8_msg.o v8_obj.o v8_r
ef.o v8_script.o v8_str.o v8_template.o v8_try_catch.o v8_value.o -LC:/git/therubyracer/ext/v8/upstream/build/v8 -L. -LC:/Ruby/lib -L. -LC:/
opt/mingw/lib -Wl,--enable-auto-image-base,--enable-auto-import   -lmsvcrt-ruby191 -lwinmm  -lshell32 -lws2_32   -rdynamic -lv8

C:/git/therubyracer/ext/v8/upstream/build/v8/libv8.a(platform-win32.o):platform-win32.cc:(.text$_ZN2v88internal4Time16SetToCurrentTimeEv+0x2
d): undefined reference to `timeGetTime@0'
C:/git/therubyracer/ext/v8/upstream/build/v8/libv8.a(platform-win32.o):platform-win32.cc:(.text$_ZN2v88internal4Time16SetToCurrentTimeEv+0x7
8): undefined reference to`timeGetTime@0'
C:/git/therubyracer/ext/v8/upstream/build/v8/libv8.a(platform-win32.o):platform-win32.cc:(.text$_ZN2v88internal2OS17TimeCurrentMillisEv+0x39
): undefined reference to `timeGetTime@0'
C:/git/therubyracer/ext/v8/upstream/build/v8/libv8.a(platform-win32.o):platform-win32.cc:(.text$_ZN2v88internal2OS17TimeCurrentMillisEv+0x8c
): undefined reference to`timeGetTime@0'

per v8-users added the **have_library('winmm') if RUBY_PLATFORM =~ /mingw/** to extconf. library was found and added to the linker automatically, still getting the same error. it's also missing references to socket related stuff, part of ws2_32. both should be available, both have been verified as being available, but neither seem to be getting linked in.

that's the big friggin mystery of the moment, but there are other quirks. note the **-LC:/opt/mingw/lib** -- somehow extconf's create_makefile pulled that out of thin air (opt doesn't even exist) and added it to ldflags. was corrected manually before trying to compile the SO.

2.3.3 has refs to MemoryBarrier, undefined in mingw. patched (with an actual patch!) a quick fix to src/platform.h -- it compiles, but haven't had a working engine to make sure it's solid.

other mingw-specific fixes are now actual patches also, but fail if called in the build flow, not sure why. they work fine from the command line, using the exact syntax from the exact working directory.
