### ISSUE TITLE
0.10.0 broke twitter-bootstrap-rails

### ISSUE THREAD

**Issue by drnic** [cowboyd/therubyracer#150]
When I upgrade to 0.10.0, twitter-bootstrap-rails's less fails with

```
error evaluating function `asset-path`: undefined method `toCSS' for [object Object]:V8::Object
  (in /Users/drnic/Sites/myapp/app/assets/stylesheets/bootstrap_and_overrides.css.less)
```

In the log it says:

```

ActionView::Template::Error (error evaluating function `asset-path`: undefined method `toCSS' for [object Object]:V8::Object
  (in /Users/drnic/Sites/myapp/app/assets/stylesheets/bootstrap_and_overrides.css.less)):
    12:     <![endif]-->
    13: 
    14:     <!-- Le styles -->
    15:     <%= stylesheet_link_tag "application", :media => "all" %>
    16: 
    17:     <!-- Le fav and touch icons -->
    18:     <link href="images/favicon.ico" rel="shortcut icon">
  app/views/layouts/application.html.erb:15:in `_app_views_layouts_application_html_erb___1749276728414096631_70195303873300'
```

The failing rows in `app/assets/stylesheets/bootstrap_and_overrides.css.less` are:

```
// Set the correct sprite paths
@iconSpritePath: asset-path('twitter/bootstrap/glyphicons-halflings.png');
@iconWhiteSpritePath: asset-path('twitter/bootstrap/glyphicons-halflings-white.png');
```

I know this is now technically a twitter-bootstrap-rails bug, but the regression was introduced in 0.10.0 of therubyracer and I was wondering if you had thoughts why?

/cc @seyhunak
