### ISSUE TITLE
won't compile on my machine since 0.10.2

### ISSUE THREAD

**Issue by fbernier** [cowboyd/therubyracer#213]
gem install therubyracer                                                                                                                                                                                                        ⏎
Building native extensions.  This could take a while...
ERROR:  Error installing therubyracer:
        ERROR: Failed to build gem native extension.

```
    /home/francois/.rvm/rubies/ruby-1.9.3-p327-turbo/bin/ruby extconf.rb
```

checking for main() in -lpthread... yes
checking for v8.h... yes
creating Makefile

make
compiling signature.cc
compiling constants.cc
compiling locker.cc
compiling exception.cc
compiling value.cc
compiling backref.cc
compiling template.cc
compiling function.cc
compiling primitive.cc
compiling script.cc
compiling constraints.cc
compiling array.cc
compiling handles.cc
compiling trycatch.cc
compiling heap.cc
compiling invocation.cc
compiling string.cc
compiling v8.cc
compiling accessor.cc
compiling rr.cc
compiling context.cc
context.cc: In static member function ‘static VALUE rr::Context::IsCodeGenerationFromStringsAllowed(VALUE)’:
context.cc:93:30: error: ‘class v8::Context’ has no member named ‘IsCodeGenerationFromStringsAllowed’
context.cc:94:1: warning: control reaches end of non-void function [-Wreturn-type]
make: **\* [context.o] Error 1

0.10.1 is fine. 0.11.0 does not work either. Ubuntu 12.10 x64 ruby 1.9.3p327 libv8-dev 3.8.9.20-2
